version: 2
jobs:
  build:
    docker:
      - image: node:10.13.0
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: example12
      - image: redis:latest

    working_directory: ~/repo

    steps:
      - checkout:
          post:
            - git fetch --all

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn install --freeze-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests & build!
      - run: yarn ci:test
      - run: yarn ci:build

      - run: git config --global user.email $GITHUB_EMAIL
      - run: git config --global user.name $GITHUB_USER

      - run: yarn new-version

      #- setup_remote_docker:
      #    docker_layer_caching: true

      #- run:
      #    name: Install Docker client
      #    command: |
      #      set -x
      #      VER="18.06.3-ce"
      #      curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #      mv /tmp/docker/* /usr/bin
      #- run: git tag
      #- run: echo 'export TAG=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sed -n 2p`' >> $BASH_ENV
      #- run: echo $TAG
      #- run: yarn ci:deploy
